name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Install Render CLI
    - name: Install Render CLI
      run: |
        curl -L https://github.com/renderinc/cli/releases/latest/download/render-cli-linux-amd64.tar.gz | tar -xz
        sudo mv render /usr/local/bin

    # Run your build commands here if needed
    - name: Install dependencies
      run: npm install

    # Run tests (optional)
    - name: Run tests
      run: npm test

    # Update Render service based on branch
    - name: Update Render service
      run: |
        if [ "${{ github.ref }}" == "refs/heads/dev" ]; then
          render services update --branch dev
        elif [ "${{ github.ref }}" == "refs/heads/main" ]; then
          render services update --branch main
        fi
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        RENDER_SERVICE_KEY: ${{ secrets.RENDER_SERVICE_KEY_${{ github.ref == 'refs/heads/dev' && 'DEV' || 'MAIN' }} }}
